## Homework 3.1

### 3.1.a
Load the data from: http://opendata.dc.gov/datasets that I have include in this github   
into a dataframe.  ( The file has been is available in directory ./data/ccp_current_csv.csv )

In [1]:
import pandas as pd
Sample= pd.read_csv("data\ccp_current_csv.csv")
Sample

STREET QUADRANT            FROMINTERSECTION  \
0               13th St       NW                  Kennedy St   
1                  S St       NW            North Capitol St   
2      Rhode Island Ave       NE            Brentwood Rd (W)   
3               Mill Rd       NW                     27th St   
4      Rhode Island Ave       NE            Brentwood Rd (M)   
5             Mellon St       SE                      5th St   
6          Nebraska Ave       NW              Northampton St   
7           Military Rd       NW                     30th St   
8          Nebraska Ave       NW                   Oliver St   
9               16th St       NW                  Alaska Ave   
10         Shoemaker St       NW                 Linnean Ave   
11         Underwood St       NW             Piney Branch Rd   
12             Elder St       NW                      7th St   
13              26th St       NW              Northampton St   
14               4th St       NW              Madison St (N)   
15         Underwood Pl       NW            North Capitol St   
16              20th St       NW                 Columbia Rd   
17          Quintana Pl       NE                      3rd St   
18         Tuckerman St       NE                  Kansas Ave   
19              Eads St       NE                     45th St   
20               4th St       SE                  Newcomb St   
21              Belt Rd       NW                  Jenifer St   
22            Oneida St       NE           New Hampshire Ave   
23      Carrollsburg Pl       SW                        O St   
24              23rd St       NW          Washington Cir (N)   
25           Kanawha St       NW                    Utah Ave   
26      Piney Branch Rd       NW                Underwood St   
27              30th St       NW               Stephenson Pl   
28              32nd St       NW                 Woodland Dr   
29              33rd St       NW            Broad Branch Ter   
..                  ...      ...                         ...   
435      New Jersey Ave       NW                        F St   
436             15th St       NE                     Ames Pl   
437     East Capitol St       BN                        C St   
438         Randolph St       NE                     25th Pl   
439    South Dakota Ave       NE                Delafield St   
440          Wheeler Rd       SE                 Congress St   
441      New Jersey Ave       NW                        H St   
442     Mount Olivet Rd       NE               Brentwood Pky   
443              Oak St       NW                     16th St   
444        Michigan Ave       NE                     14th St   
445                C St       NE                     20th St   
446        Virginia Ave       SE                  6th St (S)   
447              Oak St       NW                Brown St (N)   
448         Florida Ave       NE                New York Ave   
449  North Carolina Ave       NE         East Capitol St (E)   
450            Elder St       NW                      8th St   
451          Benning Rd       SE                        G St   
452           School St       SW                      4th St   
453             18th St       NW                        M St   
454       Longfellow St       NW                     16th St   
455             10th St       NW                        M St   
456          Woodley Rd       NW             Connecticut Ave   
457          Woodley Rd       NW           Cathedral Ave (E)   
458              3rd St       SW            Independence Ave   
459             16th St       NW                 Primrose Rd   
460          Woodley Rd       NW                  Woodley Pl   
461         Western Ave       NW         Chevy Chase Cir (E)   
462             49th St       NW                   Fulton St   
463       Quackenbos St       NE           New Hampshire Ave   
464    North Capitol St       BN  Hawaii Ave  Rock Creek Chu   

                 TOINTERSECTION  NOOFBLOCKS     

### 3.1.a  what is its shape and what does that mean?

In [2]:
Sample.shape

(465, 27)

In [3]:
Sample.mean()

NOOFBLOCKS               2.146237
YEARBUDGETED          1956.759140
PERCENTCOMPLETED       100.000000
MILES                    0.193591
XCOORD              399430.352561
YCOORD              138503.369922
LATITUDE                38.914389
LONGITUDE              -77.006578
PROJECTID             5637.784946
dtype: float64

## Homework 3.2
 What are the number of rows in each 'QUADRANT' ?

Procedure 1

In [4]:
from scipy.stats import itemfreq
import numpy as np
A=np.array(Sample)
itemfreq(A[:,1])

C:\Users\Sandeep\Anaconda2\lib\site-packages\ipykernel_launcher.py:4: DeprecationWarning: `itemfreq` is deprecated!
`itemfreq` is deprecated and will be removed in a future version. Use instead `np.unique(..., return_counts=True)`
  after removing the cwd from sys.path.


array([['BN', 12L],
       ['NE', 163L],
       ['NW', 195L],
       ['SE', 84L],
       ['SW', 11L]], dtype=object)

Procedure 2

In [5]:
Temp=np.unique(A[:,1])
BN=NE=NW=SE=SW = 0
print Temp
for x in range(len(A[:,1])):
    if A[x,1] == Temp[0]:
        BN = BN+1
    elif A[x,1] == Temp[1]:
        NE = NE+1
    elif A[x,1] == Temp[2]:
        NW = NW+1
    elif A[x,1] == Temp[3]:
        SE = SE+1
    else:
        SW=SW+1
print 'BN -->', BN  
print 'NE -->', NE
print 'NW -->', NW
print 'SE -->', SE
print 'SW -->', SW

['BN' 'NE' 'NW' 'SE' 'SW']
BN --> 12
NE --> 163
NW --> 195
SE --> 84
SW --> 11


## Homework 3.3 - Array math demonstration 
For two arrarys  

a= [1,2,3,4]  type=float

b= [5,6,7,8]  type=float

Peform the following array operations using numpy   
( show both operational use of numpy and functional (example addition operation => + vs addition function => numbpy.add() )

### 3.3.1 addition a+b 

In [6]:
import numpy as np
a = np.asarray([1,2,3,4], dtype = float)
b=np.asarray([5,6,7,8], dtype = float)


In [7]:
np.add(a,b)

array([ 6.,  8., 10., 12.])

In [8]:
a+b

array([ 6.,  8., 10., 12.])

### 3.3.2 subtraction a-b

In [9]:
np.subtract(a,b)

array([-4., -4., -4., -4.])

In [10]:
a-b

array([-4., -4., -4., -4.])

### 3.3.3 multiplication a*b

In [11]:
np.multiply(a,b)

array([ 5., 12., 21., 32.])

In [12]:
list1=a*b
print list1

[ 5. 12. 21. 32.]


### 3.3.4 divsion a/b

In [13]:
np.divide(a,b)

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [14]:
a/b

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

### 3.3.5 modulo  a%b

In [15]:
np.mod(a,b)

array([1., 2., 3., 4.])

In [16]:
a%b

array([1., 2., 3., 4.])

### 3.3.6 power  a^b

In [17]:
np.power(a,b)

array([1.0000e+00, 6.4000e+01, 2.1870e+03, 6.5536e+04])

In [18]:
a**b

array([1.0000e+00, 6.4000e+01, 2.1870e+03, 6.5536e+04])

## Homework 3.4
Find your own data and load it into a dataframe

In [19]:
import numpy as np
import pandas as pd
Own_data=pd.read_csv("data/googleplaystore.csv")
print Own_data

                                                    App        Category  \
0        Photo Editor & Candy Camera & Grid & ScrapBook  ART_AND_DESIGN   
1                                   Coloring book moana  ART_AND_DESIGN   
2     U Launcher Lite – FREE Live Cool Themes, Hide ...  ART_AND_DESIGN   
3                                 Sketch - Draw & Paint  ART_AND_DESIGN   
4                 Pixel Draw - Number Art Coloring Book  ART_AND_DESIGN   
5                            Paper flowers instructions  ART_AND_DESIGN   
6               Smoke Effect Photo Maker - Smoke Editor  ART_AND_DESIGN   
7                                      Infinite Painter  ART_AND_DESIGN   
8                                  Garden Coloring Book  ART_AND_DESIGN   
9                         Kids Paint Free - Drawing Fun  ART_AND_DESIGN   
10                              Text on Photo - Fonteee  ART_AND_DESIGN   
11              Name Art Photo Editor - Focus n Filters  ART_AND_DESIGN   
12                       

In [20]:
A=np.array(Own_data)
print(A)

[['Photo Editor & Candy Camera & Grid & ScrapBook' 'ART_AND_DESIGN' 4.1
  ... '7-Jan-18' '1.0.0' '4.0.3 and up']
 ['Coloring book moana' 'ART_AND_DESIGN' 3.9 ... '15-Jan-18' '2.0.0'
  '4.0.3 and up']
 ['U Launcher Lite \xe2\x80\x93 FREE Live Cool Themes, Hide Apps'
  'ART_AND_DESIGN' 4.7 ... '1-Aug-18' '1.2.4' '4.0.3 and up']
 ...
 ['ClearCareGo Caregiver' 'MEDICAL' 4.2 ... '25-Jul-18' '2.1.3'
  '4.1 and up']
 ['Pregnancy Calculator and Tracker app' 'MEDICAL' 4.8 ... '1-Jun-18'
  '2.6.1' '4.1 and up']
 ['All Mental disorders' 'MEDICAL' 4.5 ... '7-Jul-17' '1.1'
  '4.0.3 and up']]


## Homework 3.5
Provide an interesting analysis of the data columns ( frequency or averages )

In [21]:
from scipy.stats import itemfreq
itemfreq(A[:,3])

C:\Users\Sandeep\Anaconda2\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: `itemfreq` is deprecated!
`itemfreq` is deprecated and will be removed in a future version. Use instead `np.unique(..., return_counts=True)`
  


array([[0L, 20L],
       [1L, 8L],
       [2L, 8L],
       ...,
       [56642847L, 1L],
       [56646578L, 1L],
       [69119316L, 2L]], dtype=object)

In [22]:
itemfreq(Own_data)

C:\Users\Sandeep\Anaconda2\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: `itemfreq` is deprecated!
`itemfreq` is deprecated and will be removed in a future version. Use instead `np.unique(..., return_counts=True)`
  """Entry point for launching an IPython kernel.


array([[0L, 1L],
       [nan, 1L],
       [0L, 3L],
       ...,
       ['\xe4\xb9\x90\xe5\xb1\x8b\xe7\xbd\x91: Buying a house, selling a house, renting a house',
        1L],
       ['\xe6\xbc\xab\xe5\x92\x96 Comics - Manga,Novel and Stories', 1L],
       ['\xf0\x9f\x94\xa5 Football Wallpapers 4K | Full HD Backgrounds \xf0\x9f\x98\x8d',
        1L]], dtype=object)

In [23]:
np.unique(A[3,:])

array([4.5, 215644L, '0', '25M', '4.2 and up', '50,000,000+', '8-Jun-18',
       'ART_AND_DESIGN', 'Art & Design', 'Free', 'Sketch - Draw & Paint',
       'Teen', 'Varies with device'], dtype=object)

In [24]:
np.unique(Own_data)

array([0L, nan, 0L, ...,
       '\xe4\xb9\x90\xe5\xb1\x8b\xe7\xbd\x91: Buying a house, selling a house, renting a house',
       '\xe6\xbc\xab\xe5\x92\x96 Comics - Manga,Novel and Stories',
       '\xf0\x9f\x94\xa5 Football Wallpapers 4K | Full HD Backgrounds \xf0\x9f\x98\x8d'],
      dtype=object)

# Average

In [25]:
np.average(np.float64(A[:,3]))

892974.3695931478

In [26]:
np.mean(A[:,3])

892974.3695931478

In [27]:
print np.array_split(A,10)

[array([['Photo Editor & Candy Camera & Grid & ScrapBook',
        'ART_AND_DESIGN', 4.1, ..., '7-Jan-18', '1.0.0', '4.0.3 and up'],
       ['Coloring book moana', 'ART_AND_DESIGN', 3.9, ..., '15-Jan-18',
        '2.0.0', '4.0.3 and up'],
       ['U Launcher Lite \xe2\x80\x93 FREE Live Cool Themes, Hide Apps',
        'ART_AND_DESIGN', 4.7, ..., '1-Aug-18', '1.2.4', '4.0.3 and up'],
       ...,
       ['Tiny Scanner - PDF Scanner App', 'BUSINESS', 4.7, ...,
        '30-May-17', '1.2.6', '3.0 and up'],
       ['Fast Scanner : Free PDF Scan', 'BUSINESS', 4.5, ...,
        '11-Jul-18', '3.9.2', '4.1 and up'],
       ['Mobile Doc Scanner (MDScan) Lite', 'BUSINESS', 4.2, ...,
        '2-Aug-18', '3.4.49', '4.1 and up']], dtype=object), array([['TurboScan: scan documents and receipts in PDF', 'BUSINESS', 4.7,
        ..., '25-Mar-18', '1.5.2', '4.0 and up'],
       ['Tiny Scanner Pro: PDF Doc Scan', 'BUSINESS', 4.8, ...,
        '11-Apr-17', '3.4.6', '3.0 and up'],
       ['Box', 'BUSINESS',

In [28]:
Own_data.mean()

Rating          4.294086
Reviews    892974.369593
dtype: float64