## Homework 3.1

### 3.1.a
Load the data from: http://opendata.dc.gov/datasets that I have include in this github   
into a dataframe.  ( The file has been is available in directory ./data/ccp_current_csv.csv )

In [29]:
import pandas as pd
Sample= pd.read_csv("data\ccp_current_csv.csv")
Sample.head()

STREET QUADRANT  FROMINTERSECTION              TOINTERSECTION  \
0           13th St       NW        Kennedy St               Longfellow St   
1              S St       NW  North Capitol St                      3rd St   
2  Rhode Island Ave       NE  Brentwood Rd (W)            Brentwood Rd (M)   
3           Mill Rd       NW           27th St                  Cul De Sac   
4  Rhode Island Ave       NE  Brentwood Rd (M)  14th St  Evarts St  Montan   

   NOOFBLOCKS                 WORKDESCRIPTION  YEARBUDGETED  PERCENTCOMPLETED  \
0           1  Pavement Resurface/restoration          2004               100   
1           3                   Regular Cover          1999               100   
2           1  Pavement Resurface/restoration          2004               100   
3           1  Pavement Resurface/restoration          2004               100   
4           2  Pavement Resurface/restoration          2005               100   

      STATUS  MILES      ...             YCOORD   LATITUDE  LONGITUDE  \
0  Completed   0.07      ...       143205.11981  38.956747 -77.029694   
1  Completed   0.33      ...       138468.90256  38.914085 -77.012411   
2  Completed   0.09      ...       139574.10659  38.924041 -76.987221   
3  Completed   0.07      ...       138132.90198  38.911046 -77.054077   
4  Completed   0.16      ...       139657.25318  38.924790 -76.985068   

           PROJECTNOTE                                        PROJECTNAME  \
0                  NaN                                             FedAid   
1                  NaN                                                NaN   
2                  NaN           Fedral Aid Citywide Pavement Restoration   
3  POKA-2003-B-0048-JJ  Citywide Pavement Restoration Contract (Local ...   
4                  NaN                                                NaN   

          PROJECTMGR  PROJECTID        TEAMREP                 EMAIL  \
0    Paul Stephenson       5834        O. Hill                   NaN   
1                NaN       2467            NaN                   NaN   
2  Mohamed Abdullahi       5486   Said Cherifi   said.cherifi@dc.gov   
3    Maduabuchi Udeh       5796  Michael Jelen  Michael.Jelen@dc.gov   
4                NaN       8237            NaN                   NaN   

   CONTACTPHONE  
0  202-671-4591  
1           NaN  
2  202-671-4611  
3  202-671-4542  
4           NaN  

[5 rows x 27 columns]

### 3.1.a  what is its shape and what does that mean?

In [2]:
Sample.shape

(465, 27)

In [3]:
Sample.mean()

NOOFBLOCKS               2.146237
YEARBUDGETED          1956.759140
PERCENTCOMPLETED       100.000000
MILES                    0.193591
XCOORD              399430.352561
YCOORD              138503.369922
LATITUDE                38.914389
LONGITUDE              -77.006578
PROJECTID             5637.784946
dtype: float64

## Homework 3.2
 What are the number of rows in each 'QUADRANT' ?

Procedure 1

In [4]:
from scipy.stats import itemfreq
import numpy as np
A=np.array(Sample)
itemfreq(A[:,1])

C:\Users\Sandeep\Anaconda2\lib\site-packages\ipykernel_launcher.py:4: DeprecationWarning: `itemfreq` is deprecated!
`itemfreq` is deprecated and will be removed in a future version. Use instead `np.unique(..., return_counts=True)`
  after removing the cwd from sys.path.


array([['BN', 12L],
       ['NE', 163L],
       ['NW', 195L],
       ['SE', 84L],
       ['SW', 11L]], dtype=object)

Procedure 2

In [5]:
Temp=np.unique(A[:,1])
BN=NE=NW=SE=SW = 0
print Temp
for x in range(len(A[:,1])):
    if A[x,1] == Temp[0]:
        BN = BN+1
    elif A[x,1] == Temp[1]:
        NE = NE+1
    elif A[x,1] == Temp[2]:
        NW = NW+1
    elif A[x,1] == Temp[3]:
        SE = SE+1
    else:
        SW=SW+1
print 'BN -->', BN  
print 'NE -->', NE
print 'NW -->', NW
print 'SE -->', SE
print 'SW -->', SW

['BN' 'NE' 'NW' 'SE' 'SW']
BN --> 12
NE --> 163
NW --> 195
SE --> 84
SW --> 11


## Homework 3.3 - Array math demonstration 
For two arrarys  

a= [1,2,3,4]  type=float

b= [5,6,7,8]  type=float

Peform the following array operations using numpy   
( show both operational use of numpy and functional (example addition operation => + vs addition function => numbpy.add() )

### 3.3.1 addition a+b 

In [6]:
import numpy as np
a = np.asarray([1,2,3,4], dtype = float)
b=np.asarray([5,6,7,8], dtype = float)


In [7]:
np.add(a,b)

array([ 6.,  8., 10., 12.])

In [8]:
a+b

array([ 6.,  8., 10., 12.])

### 3.3.2 subtraction a-b

In [9]:
np.subtract(a,b)

array([-4., -4., -4., -4.])

In [10]:
a-b

array([-4., -4., -4., -4.])

### 3.3.3 multiplication a*b

In [11]:
np.multiply(a,b)

array([ 5., 12., 21., 32.])

In [12]:
list1=a*b
print list1

[ 5. 12. 21. 32.]


### 3.3.4 divsion a/b

In [13]:
np.divide(a,b)

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [14]:
a/b

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

### 3.3.5 modulo  a%b

In [15]:
np.mod(a,b)

array([1., 2., 3., 4.])

In [16]:
a%b

array([1., 2., 3., 4.])

### 3.3.6 power  a^b

In [17]:
np.power(a,b)

array([1.0000e+00, 6.4000e+01, 2.1870e+03, 6.5536e+04])

In [18]:
a**b

array([1.0000e+00, 6.4000e+01, 2.1870e+03, 6.5536e+04])

## Homework 3.4
Find your own data and load it into a dataframe

In [30]:
import numpy as np
import pandas as pd
Own_data=pd.read_csv("data/googleplaystore.csv")
print Own_data.head()

                                                 App        Category  Rating  \
0     Photo Editor & Candy Camera & Grid & ScrapBook  ART_AND_DESIGN     4.1   
1                                Coloring book moana  ART_AND_DESIGN     3.9   
2  U Launcher Lite – FREE Live Cool Themes, Hide ...  ART_AND_DESIGN     4.7   
3                              Sketch - Draw & Paint  ART_AND_DESIGN     4.5   
4              Pixel Draw - Number Art Coloring Book  ART_AND_DESIGN     4.3   

   Reviews  Size     Installs  Type Price Content Rating  \
0      159   19M      10,000+  Free     0       Everyone   
1      967   14M     500,000+  Free     0       Everyone   
2    87510  8.7M   5,000,000+  Free     0       Everyone   
3   215644   25M  50,000,000+  Free     0           Teen   
4      967  2.8M     100,000+  Free     0       Everyone   

                      Genres Last Updated         Current Ver   Android Ver  
0               Art & Design     7-Jan-18               1.0.0  4.0.3 and up  
1 

In [32]:
A=np.array(Own_data)
print(A)

[['Photo Editor & Candy Camera & Grid & ScrapBook' 'ART_AND_DESIGN' 4.1
  ... '7-Jan-18' '1.0.0' '4.0.3 and up']
 ['Coloring book moana' 'ART_AND_DESIGN' 3.9 ... '15-Jan-18' '2.0.0'
  '4.0.3 and up']
 ['U Launcher Lite \xe2\x80\x93 FREE Live Cool Themes, Hide Apps'
  'ART_AND_DESIGN' 4.7 ... '1-Aug-18' '1.2.4' '4.0.3 and up']
 ...
 ['ClearCareGo Caregiver' 'MEDICAL' 4.2 ... '25-Jul-18' '2.1.3'
  '4.1 and up']
 ['Pregnancy Calculator and Tracker app' 'MEDICAL' 4.8 ... '1-Jun-18'
  '2.6.1' '4.1 and up']
 ['All Mental disorders' 'MEDICAL' 4.5 ... '7-Jul-17' '1.1'
  '4.0.3 and up']]


## Homework 3.5
Provide an interesting analysis of the data columns ( frequency or averages )

In [21]:
from scipy.stats import itemfreq
itemfreq(A[:,3])

C:\Users\Sandeep\Anaconda2\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: `itemfreq` is deprecated!
`itemfreq` is deprecated and will be removed in a future version. Use instead `np.unique(..., return_counts=True)`
  


array([[0L, 20L],
       [1L, 8L],
       [2L, 8L],
       ...,
       [56642847L, 1L],
       [56646578L, 1L],
       [69119316L, 2L]], dtype=object)

In [22]:
itemfreq(Own_data)

C:\Users\Sandeep\Anaconda2\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: `itemfreq` is deprecated!
`itemfreq` is deprecated and will be removed in a future version. Use instead `np.unique(..., return_counts=True)`
  """Entry point for launching an IPython kernel.


array([[0L, 1L],
       [nan, 1L],
       [0L, 3L],
       ...,
       ['\xe4\xb9\x90\xe5\xb1\x8b\xe7\xbd\x91: Buying a house, selling a house, renting a house',
        1L],
       ['\xe6\xbc\xab\xe5\x92\x96 Comics - Manga,Novel and Stories', 1L],
       ['\xf0\x9f\x94\xa5 Football Wallpapers 4K | Full HD Backgrounds \xf0\x9f\x98\x8d',
        1L]], dtype=object)

In [23]:
np.unique(A[3,:])

array([4.5, 215644L, '0', '25M', '4.2 and up', '50,000,000+', '8-Jun-18',
       'ART_AND_DESIGN', 'Art & Design', 'Free', 'Sketch - Draw & Paint',
       'Teen', 'Varies with device'], dtype=object)

In [24]:
np.unique(Own_data)

array([0L, nan, 0L, ...,
       '\xe4\xb9\x90\xe5\xb1\x8b\xe7\xbd\x91: Buying a house, selling a house, renting a house',
       '\xe6\xbc\xab\xe5\x92\x96 Comics - Manga,Novel and Stories',
       '\xf0\x9f\x94\xa5 Football Wallpapers 4K | Full HD Backgrounds \xf0\x9f\x98\x8d'],
      dtype=object)

# Average

In [25]:
np.average(np.float64(A[:,3]))

892974.3695931478

In [26]:
np.mean(A[:,3])

892974.3695931478

In [27]:
print np.array_split(A,10)

[array([['Photo Editor & Candy Camera & Grid & ScrapBook',
        'ART_AND_DESIGN', 4.1, ..., '7-Jan-18', '1.0.0', '4.0.3 and up'],
       ['Coloring book moana', 'ART_AND_DESIGN', 3.9, ..., '15-Jan-18',
        '2.0.0', '4.0.3 and up'],
       ['U Launcher Lite \xe2\x80\x93 FREE Live Cool Themes, Hide Apps',
        'ART_AND_DESIGN', 4.7, ..., '1-Aug-18', '1.2.4', '4.0.3 and up'],
       ...,
       ['Tiny Scanner - PDF Scanner App', 'BUSINESS', 4.7, ...,
        '30-May-17', '1.2.6', '3.0 and up'],
       ['Fast Scanner : Free PDF Scan', 'BUSINESS', 4.5, ...,
        '11-Jul-18', '3.9.2', '4.1 and up'],
       ['Mobile Doc Scanner (MDScan) Lite', 'BUSINESS', 4.2, ...,
        '2-Aug-18', '3.4.49', '4.1 and up']], dtype=object), array([['TurboScan: scan documents and receipts in PDF', 'BUSINESS', 4.7,
        ..., '25-Mar-18', '1.5.2', '4.0 and up'],
       ['Tiny Scanner Pro: PDF Doc Scan', 'BUSINESS', 4.8, ...,
        '11-Apr-17', '3.4.6', '3.0 and up'],
       ['Box', 'BUSINESS',

In [28]:
Own_data.mean()

Rating          4.294086
Reviews    892974.369593
dtype: float64